//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public long Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string MallId { get; set; }
        public string MemberId { get; set; }
        public string HappyGoNo { get; set; }
        public string Name { get; set; }
        public string ChildName { get; set; }
        public string CardNumber { get; set; }
        public string MuId { get; set; }
        public string RealMuid { get; set; }
        public Nullable<int> CardTypeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> MemberBirth { get; set; }
        public Nullable<System.DateTime> ChildBirth { get; set; }
        public Nullable<System.DateTime> DueDay { get; set; }
        public string Cellphone { get; set; }
        public Nullable<long> Checker { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<long> ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsUse { get; set; }
    }
}
